[versions]
android-gradlePlugin = "7.0.3"
android-desugar = "1.1.5"

kotlin = "1.5.31"
kotlinx-coroutines = "1.5.2"
kotlinx-serialization = "1.3.0"

androidx-activity = "1.3.1"
androidx-compose = "1.1.0-alpha05"
androidx-fragment = "1.4.0-alpha09"
androidx-lifecycle = "2.4.0-beta01"
androidx-navigation = "2.4.0-alpha09"
androidx-room = "2.3.0"
androidx-paging = "3.0.1"
google-hilt = "2.38.1"
google-accompanist = "0.17.0"
squareup-okhttp = "4.9.1"
coil = "1.3.2"

[plugins]
detekt = "io.gitlab.arturbosch.detekt:1.18.0"

[libraries]
android-tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
android-tools-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-annotation-annotation = "androidx.annotation:annotation:1.2.0"
androidx-core-coreKtx = "androidx.core:core-ktx:1.5.0"
androidx-appcompat-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }

androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-room-roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

androidx-paging-commonKtx = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
androidx-paging-runtimeKtx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha12"

google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "google-hilt" }

google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "google-accompanist" }
google-accompanist-insetsUi = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "google-accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }

google-gms-googleServices = "com.google.gms:google-services:4.3.10"
google-firebase-crashlyticsGradle = "com.google.firebase:firebase-crashlytics-gradle:2.7.1"
google-firebase-crashlyticsKtx = "com.google.firebase:firebase-crashlytics-ktx:18.2.1"
google-firebase-analyticsKtx = "com.google.firebase:firebase-analytics-ktx:19.0.0"

squareup-okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp" }
squareup-okhttp-logginInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-okhttp" }
squareup-retrofit-retrofit = "com.squareup.retrofit2:retrofit:2.9.0"

jakewharton-retrofit-kotlinxSerializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
jakewharton-timber-timber = "com.jakewharton.timber:timber:4.7.1"

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
