complexity:
  LongParameterList:
    functionThreshold: 18
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotated: [ 'Preview' ]
  LongMethod:
    threshold: 180

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  ReturnCount:
    active: false
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'

TwitterCompose:
  ViewModelInjection:
    active: false
