name: Finish release
on:
  workflow_dispatch:
    inputs:
      mainBranch:
        description: 'Main branch to merge into'
        type: string
        default: main

jobs:
  finish_release:
    name: Finish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download FOB CLI
        run: 'curl https://api.bitbucket.org/2.0/repositories/fobsolutions/fob-cli/downloads/fob-cli-1.0.1.jar -o fob-cli.jar -H "Authorization: Bearer $FOB_CLI_ACCESS_TOKEN" -L -s'
        env:
          FOB_CLI_ACCESS_TOKEN: ${{ secrets.FOB_CLI_ACCESS_TOKEN }}
      - name: Fetch main branch (so diff is possible)
        run: |
          git checkout ${{ inputs.mainBranch }}
          git checkout $BITBUCKET_BRANCH
      - name: Validate that release does not exist yet and is properly merged
        run: |
          VERSION_NAME=`java -jar fob-cli.jar project get-version-name`
          '! git ls-remote --exit-code --tags origin refs/tags/$VERSION_NAME || (exit 2)'
          'git diff --exit-code ${{ inputs.mainBranch }}... -- ":(exclude)version.properties" || (exit 2)'
      - name: Create a tag
        run: |
          git tag -a $VERSION_NAME -m "Release version $VERSION_NAME"
          git push origin $VERSION_NAME
