name: CI for master branch
on:
  push:
    branches: [ master ]

jobs:
  master:
    name: Check and assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all checks
        run: ./gradlew --no-daemon clean check
      - name: Assemble
        run: ./gradlew --no-daemon clean assemble
