name: Update version code and publish the app
on:
  push:
    branches:
      - main
      - 'release/**'

env:
  GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download FOB CLI
        run: 'curl https://api.bitbucket.org/2.0/repositories/fobsolutions/fob-cli/downloads/fob-cli-1.0.1.jar -o fob-cli.jar -H "Authorization: Bearer $FOB_CLI_ACCESS_TOKEN" -L -s'
        env:
          FOB_CLI_ACCESS_TOKEN: ${{ secrets.FOB_CLI_ACCESS_TOKEN }}
      - name: Update version code
        run: java -jar fob-cli.jar project update-version $GITHUB_RUN_NUMBER
      - name: Assemble dev app
        run: ./gradlew app:bundleDevRelease --no-daemon -Psnapshot
        env:
          DEV_RELEASE_PASSWORD: ${{ secrets.DEV_RELEASE_PASSWORD }}
      - name: Publish to Google Play
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="google_credentials.json"
          echo $PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA > $GOOGLE_APPLICATION_CREDENTIALS
          COMMIT_MESSAGE=`git log --format=%B -n 1 $GITHUB_SHA`
          java -jar fob-cli.jar play-store deploy app/build/outputs/bundle/devRelease/app-dev-release.aab --package-name com.sensorfields.chore.dev --release-notes "$COMMIT_MESSAGE"
        env:
          PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      - name: Commit and push changes
        run: |
          git add .
          git restore --staged fob-cli.jar
          git restore --staged $GOOGLE_APPLICATION_CREDENTIALS
          git commit -m "Version code $GITHUB_RUN_NUMBER"
          git push
