name: Update version code and publish the app
on:
  push:
    branches:
      - main
      - 'release/**'

env:
  GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download FOB CLI
        run: |
          curl https://api.bitbucket.org/2.0/repositories/fobsolutions/fob-cli/downloads/fob-cli-1.0.2.jar \
          -o fob-cli.jar \
          -H "Authorization: Bearer $FOB_CLI_ACCESS_TOKEN" \
          -L -s
        env:
          FOB_CLI_ACCESS_TOKEN: ${{ secrets.FOB_CLI_ACCESS_TOKEN }}
      - uses: onyxmueller/build-tag-number@v1
        id: buildnumber
        with:
          token: ${{ secrets.github_token }}
      - name: Update version code
        run: java -jar fob-cli.jar project update-version ${{ steps.buildnumber.outputs.build_number }}
      - name: Assemble dev snapshot app
        run: ./gradlew --no-daemon app:bundleDevRelease -Psnapshot
        env:
          DEV_RELEASE_PASSWORD: ${{ secrets.DEV_RELEASE_PASSWORD }}
      - name: Publish dev snapshot app to Google Play
        run: |
          echo $PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA > $GOOGLE_APPLICATION_CREDENTIALS
          COMMIT_MESSAGE=`git log --format=%B -n 1 $GITHUB_SHA`
          java -jar fob-cli.jar play-store deploy \
          app/build/outputs/bundle/devRelease/app-dev-release.aab \
          --package-name com.sensorfields.chore.dev \
          --release-notes "$COMMIT_MESSAGE"
        env:
          PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.properties
          git commit -m "Version code ${{ steps.buildnumber.outputs.build_number }} [skip ci]"
          git push
