name: Publish release app
on:
  push:
    tags:
      - '**'

env:
  GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Assemble dev app
        run: ./gradlew app:bundleDevRelease --no-daemon
        env:
          DEV_RELEASE_PASSWORD: ${{ secrets.DEV_RELEASE_PASSWORD }}
#      - name: Publish to Google Play
#        run: |
#          export GOOGLE_APPLICATION_CREDENTIALS="google_credentials.json"
#          echo $PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA > $GOOGLE_APPLICATION_CREDENTIALS
#          COMMIT_MESSAGE=`git log --format=%B -n 1 $GITHUB_SHA`
#          java -jar fob-cli.jar play-store deploy app/build/outputs/bundle/devRelease/app-dev-release.aab --package-name com.sensorfields.chore.dev --release-notes "$COMMIT_MESSAGE"
#        env:
#          PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      - name: Delete release branch
        run: git push origin -d release/GITHUB_REF_NAME 2> /dev/null || echo "Branch release/GITHUB_REF_NAME already deleted"
