name: Publish release app
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Assemble dev app
        run: ./gradlew --no-daemon app:bundleDevRelease
        env:
          DEV_RELEASE_PASSWORD: ${{ secrets.DEV_RELEASE_PASSWORD }}
      - name: Publish dev app to Google Play
        run: |
          echo $PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA > $GOOGLE_APPLICATION_CREDENTIALS
          java -jar fob-cli.jar play-store deploy \
          app/build/outputs/bundle/devRelease/app-dev-release.aab \
          --package-name com.sensorfields.chore.dev \
        env:
          PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.PLAY_GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      - name: Delete release branch
        run: git push origin -d release/$GITHUB_REF_NAME 2> /dev/null || echo "Branch release/$GITHUB_REF_NAME already deleted"
