name: CI for pull requests
on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run all checks
        run: ./gradlew --no-daemon clean check
